# Generated by Django 5.1.3 on 2024-12-02 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
                ('preparation_time', models.IntegerField()),
                ('preparation_time_unit', models.CharField(max_length=80)),
                ('severings', models.IntegerField()),
                ('severings_unit', models.CharField(max_length=80)),
                ('preparation_step', models.TextField()),
                ('preparation_step_is_html', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('BOLOS', 'BOLOS'), ('TORTAS', 'TORTAS'), ('SOBREMESA', 'SOBREMESA'), ('RÁPIDAS', 'RÁPIDAS'), ('DATAS_ESPECIAIS', 'DATAS_ESPECIAIS'), ('CARNES', 'CARNES'), ('AVES', 'AVES'), ('PEIXES_E_FRUTOS_DO_MAR', 'PEIXES_E_FRUTOS_DO_MAR'), ('SALADAS_E_MOLHOS', 'SALADAS_E_MOLHOS'), ('SOPAS', 'SOPAS'), ('MASSAS', 'MASSAS'), ('BEBIDAS', 'BEBIDAS'), ('COMIDA_SAUDÁVEL', 'COMIDA_SAUDÁVEL'), ('PRATO_ÚNICO', 'PRATO_ÚNICO'), ('OUTROS', 'OUTROS')], max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
